# Workflow
name: Hello

on:
  workflow_dispatch:
    

# Jobs
jobs:
  say-hello:
  

# Steps
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"

# Action
